[workspace]
resolver = "2"
members = [ 
  "cercis",
  "html",
  "rsx"
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
cercis-rsx = { path = "rsx" }
cercis-html = { path = "html" }

