[workspace]
resolver = "2"
members = [ 
  "component", 
  "core",
  "html",
  "rsx"
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
cercis-rsx = { path = "rsx" }
cercis-component = { path = "component" }
cercis-html = { path = "html" }

