[package]
name = "cercis"
version.workspace = true
edition = "2021"

[dependencies]
cercis-rsx.workspace = true
cercis-component.workspace = true
cercis-html.workspace = true
typed-builder = "0.18.2"

