[package]
name = "cercis-rsx"
version.workspace = true
edition = "2021"

[lib]
proc-macro = true

[dependencies]
cercis-html = { path = "../html"}
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = "2.0.58"
